have configure check for PCC_HOME

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3177,6 +3177,19 @@ fi
 
 BIGLOO_VERSION=$ac_prog_version
 
+# XXX for now we require PCC_HOME variable
+{ echo "$as_me:$LINENO: checking for existence of PCC_HOME variable" >&5
+echo $ECHO_N "checking for existence of PCC_HOME variable... $ECHO_C" >&6; }
+if test -z $PCC_HOME ; then
+  { { echo "$as_me:$LINENO: error: You *MUST* define the PCC_HOME environment variable to point to the source root directory!" >&5
+echo "$as_me: error: You *MUST* define the PCC_HOME environment variable to point to the source root directory!" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  { echo "$as_me:$LINENO: result: $PCC_HOME" >&5
+echo "${ECHO_T}$PCC_HOME" >&6; }
+fi
+
+
 # curl
 
   succeeded=no
@@ -8161,6 +8174,8 @@ fi
 echo "
                     Roadsend PHP Configuration Summary
                   ======================================
+
+        PCC_HOME:                 ${PCC_HOME}
 
 	prefix:                   ${prefix}
         libdir:                   ${libdir}
